name: Deploy with Environment Variables

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "VITE_API_KEY=${{ secrets.API_KEY }}" > .env
          echo "VITE_API_URL=${{ secrets.API_URL }}" >> .env
          echo "VITE_API_LAYOUT=${{ secrets.API_LAYOUT }}" >> .env

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Setup Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy project
        run: npm run deploy
